log:
  log_dir: 'log'
  chkpt_dir: 'chkpt'


arcface:
  chkpt_path: 'Arcface.pth'
  vector_size: 128

data:
  dataset_dir: './results/train/'
  valset_dir: './results/val'

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 1

  num_workers: 24
  grad_clip: 0.0